### ISSUE TITLE
mks-plugin for cura 3.5

### ISSUE THREAD

**Issue by Mindreader12345** [makerbase-mks/Software#7]
Hello, 

everything works, but now in cura 3.5 MKS-plugin doesn´t work.
Is it possible to make it work ?

Greetings ...

**Comment by stef-ladefense** [comment]
+1

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/Software/blob/master/MKS Plugin/MKS Plugin3.5↑.rar

**Comment by stef-ladefense** [comment]
404 ! very good upgrade

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/Software/blob/master/MKS Plugin/MKS Plugin3.6.rar

**Comment by makerbase-mks** [comment]
We updated the plugin file.
https://github.com/makerbase-mks/Software/blob/master/MKS Plugin/MKS Plugin3.5↑.rar

**Comment by sna1363** [comment]
It still does not work...

I have tried different versions of Cura with different versions of MKS plug-in. None of them has worked!
Tried Cura 3.5, 3.5.1, 3.6 with "https://github.com/makerbase-mks/Software/blob/master/MKS Plugin/MKS Plugin3.5↑.rar" no success. Tried older Cura versions with other releases of MKS plug-in, again, no success. Whether CURA crashes or the plug-in does not work/activated.

I have bought a MKS TFT wifi, and I expected that I can use it to transfer files via WiFi to the SD card inserted to the TFT. Except some basic actions, initiating a print from MKS app, this WiFi module has no other advantages so far!

**Comment by stef-ladefense** [comment]
oh it's amazing that it does not work ... or not
